### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by cenotechnology** [fabioasdias/RefCliq#10]
Dear All,
Many thanks for RefCliq. I have been trying to install RefCliq, but received the following error message.
Could you please help me?
thanks for your support.
`pip install refcliq`
`error: Command "g++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/Sadrac/opt/anaconda3/include -arch x86_64 -I/Users/Sadrac/opt/anaconda3/include -arch x86_64 -I/Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -c sklearn/svm/src/libsvm/libsvm_template.cpp -o build/temp.macosx-10.9-x86_64-3.8/sklearn/svm/src/libsvm/libsvm_template.o -MMD -MF build/temp.macosx-10.9-x86_64-3.8/sklearn/svm/src/libsvm/libsvm_template.o.d" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
nning setup.py clean for scikit-learn
  Building wheel for python-levenshtein (setup.py) ... [?25lerror
  ERROR: Command errored out with exit status 1:
   command: /Users/Sadrac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/python-levenshtein_e2983cdd08ab485bb18a73a523a99a55/setup.py'"'"'; __file__='"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/python-levenshtein_e2983cdd08ab485bb18a73a523a99a55/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-wheel-rsu2g4jd
       cwd: /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/python-levenshtein_e2983cdd08ab485bb18a73a523a99a55/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/Levenshtein
  copying Levenshtein/StringMatcher.py -> build/lib.macosx-10.9-x86_64-3.8/Levenshtein
  copying Levenshtein/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/Levenshtein
  running egg_info
  writing python_Levenshtein.egg-info/PKG-INFO
  writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
  writing entry points to python_Levenshtein.egg-info/entry_points.txt
  writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
  writing requirements to python_Levenshtein.egg-info/requires.txt
  writing top-level names to python_Levenshtein.egg-info/top_level.txt
  reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  copying Levenshtein/_levenshtein.c -> build/lib.macosx-10.9-x86_64-3.8/Levenshtein
  copying Levenshtein/_levenshtein.h -> build/lib.macosx-10.9-x86_64-3.8/Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/Levenshtein
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Sadrac/opt/anaconda3/include -arch x86_64 -I/Users/Sadrac/opt/anaconda3/include -arch x86_64 -I/Users/Sadrac/opt/anaconda3/include/python3.8 -c Levenshtein/_levenshtein.c -o build/temp.macosx-10.9-x86_64-3.8/Levenshtein/_levenshtein.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-levenshtein
nning setup.py clean for python-levenshtein
Failed to build numpy scikit-learn python-levenshtein
Installing collected packages: numpy, scipy, python-levenshtein, fuzzywuzzy, tqdm, scikit-learn, python-louvain, googlemaps, refcliq
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Uninstalling numpy-1.19.4:
      Successfully uninstalled numpy-1.19.4
    Running setup.py install for numpy ... [?25lerror
    ERROR: Command errored out with exit status 1:
     command: /Users/Sadrac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py'"'"'; __file__='"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-record-1bd3sode/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Sadrac/opt/anaconda3/include/python3.8/numpy
         cwd: /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/
    Complete output (220 lines):
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    blis_info:
    customize UnixCCompiler
      libraries blis not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    openblas_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_3_10_blas_info:
    customize UnixCCompiler
      libraries satlas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_blas_info:
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    accelerate_info:
      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    
      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    
    /bin/sh: svnversion: command not found
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/Users/Sadrac/opt/anaconda3/lib', '/usr/lib']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /Users/Sadrac/opt/anaconda3/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
      FOUND:
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
    
    /Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize NAGFCompiler
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize IBMFCompiler
    Could not locate executable xlf90
    Could not locate executable xlf
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    don't know how to compile Fortran code on platform 'posix'
    C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/Sadrac/opt/anaconda3/include -arch x86_64 -I/Users/Sadrac/opt/anaconda3/include -arch x86_64
    
    compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/Sadrac/opt/anaconda3/include/python3.8 -c'
    gcc: _configtest.c
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py", line 415, in <module>
        setup_package()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py", line 407, in setup_package
        setup(**metadata)
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/build.py", line 47, in run
        old_build.run(self)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/Sadrac/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/build_src.py", line 148, in run
        self.build_sources()
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/build_src.py", line 159, in build_sources
        self.build_library_sources(*libname_info)
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/build_src.py", line 292, in build_library_sources
        sources = self.generate_sources(sources, (lib_name, build_info))
      File "/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/numpy/distutils/command/build_src.py", line 375, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 667, in get_mathlib_info
        raise RuntimeError("Broken toolchain: cannot link a simple C program")
    RuntimeError: Broken toolchain: cannot link a simple C program
    ----------------------------------------
g back uninstall of numpy
  Moving to /Users/Sadrac/opt/anaconda3/bin/f2py
   from /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-uninstall-h9tpeejr/f2py
  Moving to /Users/Sadrac/opt/anaconda3/bin/f2py3
   from /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-uninstall-h9tpeejr/f2py3
  Moving to /Users/Sadrac/opt/anaconda3/bin/f2py3.8
   from /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-uninstall-h9tpeejr/f2py3.8
  Moving to /Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/numpy-1.19.4.dist-info/
   from /Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/~umpy-1.19.4.dist-info
  Moving to /Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/numpy/
   from /Users/Sadrac/opt/anaconda3/lib/python3.8/site-packages/~umpy
ERROR: Command errored out with exit status 1: /Users/Sadrac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py'"'"'; __file__='"'"'/private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-install-_rj4ipsr/numpy_0fe087a82503447cbeedc607502da456/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w5/nznh8qr123n947zr160qpz_40000gp/T/pip-record-1bd3sode/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Sadrac/opt/anaconda3/include/python3.8/numpy Check the logs for full command output.
Note: you may need to restart the kernel to use updated packages.`

**Comment by fabioasdias** [comment]
I don't have a mac to test it, but python-levenshtein is sometimes tricky to install. https://github.com/ztane/python-Levenshtein#id1

My suggestion is that you try to install it directly, then when you try to install refcliq, they would already be there. 

python-levenshtein=0.12.0 gets pulled by fuzzywuzzy: https://github.com/seatgeek/fuzzywuzzy/blob/master/setup.py#L26
